"""
Extract data witness variables from loop invariant pure clauses.

Scans for patterns like `t -> data == w` where 'data' is a configured data
field and 'w' is a pre-existing existential variable.  These witnesses are
part of the abstract loop state but are not generated by predicate translation.
"""

import json
import os
import re
from typing import List, Optional, Set


_DATA_FIELDS: Set[str] = set()


def _load_data_fields() -> Set[str]:
    global _DATA_FIELDS
    if _DATA_FIELDS:
        return _DATA_FIELDS
    json_path = os.path.join(os.path.dirname(__file__), '..', 'data', 'data_fields.json')
    json_path = os.path.normpath(json_path)
    with open(json_path, 'r') as f:
        data = json.load(f)
    _DATA_FIELDS = set(data.get('data_fields', []))
    return _DATA_FIELDS


def extract_data_witnesses(
    translated_inv: str,
    pre_existing_vars: List[str],
) -> List[str]:
    """Return pre-existing existential vars that appear in data field match clauses.

    A data field match clause has the form ``<expr> -> <field> == <var>`` where
    ``<field>`` is in the configured data_fields registry and ``<var>`` is one of
    *pre_existing_vars*.

    Args:
        translated_inv: The full translated invariant text (after exists merging).
        pre_existing_vars: Existential variable names from the original annotation
            (before predicate translation added new ones).

    Returns:
        Ordered list of matched variable names (preserving first-occurrence order,
        no duplicates).
    """
    if not pre_existing_vars:
        return []

    data_fields = _load_data_fields()
    if not data_fields:
        return []

    var_set = set(pre_existing_vars)

    # Match both orderings:
    #   <expr> -> <field> == <var>   (e.g. t -> data == w)
    #   <var> == <expr> -> <field>   (e.g. v == t -> data)
    pattern_right = re.compile(r'(\w+)\s*->\s*(\w+)\s*==\s*(\w+)')
    pattern_left = re.compile(r'(\w+)\s*==\s*(\w+)\s*->\s*(\w+)')

    seen = set()
    result = []

    for m in pattern_right.finditer(translated_inv):
        field = m.group(2)
        var = m.group(3)
        if field in data_fields and var in var_set and var not in seen:
            seen.add(var)
            result.append(var)

    for m in pattern_left.finditer(translated_inv):
        var = m.group(1)
        field = m.group(3)
        if field in data_fields and var in var_set and var not in seen:
            seen.add(var)
            result.append(var)

    return result


def extract_pre_existing_vars(original_content: str) -> List[str]:
    """Extract existential variable names from the original annotation text.

    Parses the leading ``exists v1 v2 ...,`` clause (if any) and returns the
    variable names.  These are the vars the user wrote, before predicate
    translation added generated ones.
    """
    m = re.match(r'^\s*exists\s+(.*?),', original_content, re.DOTALL)
    if not m:
        return []
    return m.group(1).split()
